services:
  ollama:
    image: ollama/ollama:0.9.5
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./.scripts/ollama-entrypoint.sh:/entrypoint.sh
    entrypoint: ["/entrypoint.sh"]
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 10s
      retries: 5
  rag-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-app
    depends_on:
      ollama:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_store:/app/chroma_store
      - ./sample_data:/app/sample_data
      - ./logs:/app/logs
      - ./models:/app/models        # Required for LLAMA_CPP_BACKEND
    environment:
      - OLLAMA_CLIENT_URL=http://ollama:11434
      - HOST=0.0.0.0
      - PORT=8000
      - LLM_BACKEND=OLLAMA_BACKEND

volumes:
  ollama_data: