services:
  rag-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_store:/app/chroma_store
      - ./sample_data:/app/sample_data
      - ./logs:/app/logs
      - ./models:/app/models
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - LLM_BACKEND=${LLM_BACKEND:-OLLAMA_BACKEND}
      - OLLAMA_CLIENT_URL=http://host.docker.internal:11434
    command: ["python", "main.py"]
